config/routes.rb
TheSwarm::Application.routes.draw do
  resource :account, :only => [:show,:edit,:update], :controller => 'accounts'
  resources :users, :only => [:index,:new,:create]
  resource :user, :only => [:edit,:update], :controller => 'users'
  
  resources :campaigns, :only => [:index,:show,:new,:create,:destroy] do
    resources :messages, :only => [:new,:create,:show]
  end
  
  resources :contacts do
    resources :subscriptions, :only => [:new,:create,:destroy]
  end
  
  resource :login, :only => [:new,:create,:destroy]

  root :to => 'campaigns#index'
end

app/models/login.rb
class Login
  include ActiveModel::Validations
  extend ActiveModel::Naming
  
  attr_accessor :email, :password
  validates_presence_of :email, :password

  def initialize(attributes = {})
    attributes ||= {}
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def find_authenticated()
    user = User.find_by_email(email)
    return user && user.authenticate(password) ? user : nil
  end  

  def to_model
    self
  end
  
  def to_key; end
  def to_param; end
  
  def persisted?
    false
  end  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    @login = Login.new
  end
  
  def create
    @login = Login.new(params[:login])
    
    if user = @login.find_authenticated
      session[:user_id] = user.id
      redirect_to root_path, :notice => "Logged in!"
    else
      @login.errors.add(:email, "Invalid email or password")
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to new_login_path, :notice => "Logged out!"
  end
end

app/views/logins/new.html.erb
<div class="ui-body ui-body-a">
  <h1>Enter the Swarm</h1>

  <%= form_for @login, :url => login_url do |f| %>
  <p>
    <%= f.label :email, 'Email' %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password, 'Password' %>
    <%= f.password_field :password %>
  </p>
    <p><%= f.submit 'Login' %></p>
  <% end %>
  <br />
</div>
<%= render "layouts/partials/validation_errors", :model => @login %>