config/routes.rb
TheSwarm::Application.routes.draw do
  resource :account, :only => [:show,:edit,:update], :controller => 'accounts'
  resources :users, :only => [:index,:new,:create]
  resource :user, :only => [:edit,:update], :controller => 'users'
  
  resources :campaigns, :only => [:index,:show,:new,:create,:destroy] do
    resources :messages, :only => [:new,:create,:show]
  end
  
  resources :contacts do
    resources :subscriptions, :only => [:new,:create,:destroy]
  end
  
  resource :login, :only => [:new,:create,:destroy]

  root :to => 'campaigns#index'
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :account
  has_many :subscriptions, :dependent => :destroy
  
  validates_presence_of :name
  validates_format_of :phone, :with => /^(1?(-?\d{3})-?)?(\d{3})(-?\d{4})$/, :message => 'must 7, 10, or 11 digit US phone number',
                      :unless => Proc.new { |m| m.phone.blank? }  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate
  
  def index
    @contacts = Contact.find_all_by_account_id(current_user.account_id)    
  end

  def new
    @account = current_user.account
    @contact = @account.contacts.build
  end

  def edit
    @contact = Contact.find_by_id_and_account_id(params[:id], current_user.account_id)
    @subscriptions = @contact.subscriptions.includes(:campaign)
  end

  def create
    @account = current_user.account
    @contact = @account.contacts.new(params[:contact])

    if @contact.save
      flash[:notice] = "Contact created!"
      redirect_to contacts_path
    else
      render :action => "new"
    end      
  end
end

app/views/contacts/_contact.html.erb
<li>
  <%= link_to(edit_contact_path(contact)) do %>
    <div class="ui-grid-b">
      <div class="ui-block-a"><%= contact.name %></div>
      <div class="ui-block-b"><%= contact.phone %></div>
    </div>
  <% end %>
</li>

app/views/contacts/edit.html.erb
<% content_for :right_header do %>
  <%= link_to 'Add Subscription', new_contact_subscription_path(@contact), 'data-theme' => 'a', 'data-icon' => 'plus', 'class' => 'ui-btn-right' %>
<% end %>

<div class="ui-body ui-body-a">
  <h1>Contact: <%= @contact.name %></h1>
  <div class="ui-body ui-body-b">
    <h4>Phone: <%= @contact.phone %></h4>
  </div>

  <h2>Campaigns:</h2>
  <ul data-role="listview" data-theme="d" data-inset="true">
	<% unless @subscriptions.blank? %>
      <%= render @subscriptions %>
    <% else %>
      <li data-role="list-divider">No campaign subscriptions</li>
    <% end %>
  </ul>
  <br />
</div>

app/views/contacts/index.html.erb
<% content_for :right_header do %>
  <%= link_to 'Add New Contact', new_contact_path, 'data-theme' => 'a', 'data-icon' => 'plus', 'class' => 'ui-btn-right' %>
<% end %>

<div class="ui-body ui-body-a">
  <h2>Contacts</h2>
  <ul data-role="listview" data-theme="d" data-inset="true">
	<% unless @contacts.blank? %>
      <%= render @contacts %>
    <% else %>
      <li data-role="list-divider"><h4>No Contacts</h4></li>
    <% end %>
  </ul>
</div>

app/views/contacts/new.html.erb
<div class="ui-body ui-body-a">
  <h1>New Contact</h1>

  <%= form_for(@contact) do |f| %>
    <p>
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :phone, 'Phone' %>
      <%= f.telephone_field :phone %>
    </p>

    <p><%= f.submit 'Save' %></p>
  <% end %>
  <br />
</div>
<%= render "layouts/partials/validation_errors", :model => @contact %>