config/routes.rb
TheSwarm::Application.routes.draw do
  resource :account, :only => [:show,:edit,:update], :controller => 'accounts'
  resources :users, :only => [:index,:new,:create]
  resource :user, :only => [:edit,:update], :controller => 'users'
  
  resources :campaigns, :only => [:index,:show,:new,:create,:destroy] do
    resources :messages, :only => [:new,:create,:show]
  end
  
  resources :contacts do
    resources :subscriptions, :only => [:new,:create,:destroy]
  end
  
  resource :login, :only => [:new,:create,:destroy]

  root :to => 'campaigns#index'
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :account, :counter_cache => true
  has_many :messages, :dependent => :destroy
  has_many :subscriptions, :dependent => :destroy  
  
  validates_presence_of :account_id
  validates_presence_of :name
  validates_format_of :name, :with => /^[\w-]+$/i, :message => 'must be letters or numbers',
                      :unless => Proc.new { |m| m.name.blank? }
  
  before_create :save_sns
  before_destroy :delete_sns
  
  def name=(v)
    write_attribute(:name, v ? v.upcase : v)
  end  
  
  def update_subscriptions
    missing_arn = subscriptions.where(:subscription_arn => nil)
    logger.info 'missing_arn = ' +missing_arn.inspect
    return if missing_arn.blank?

    topic = AWS::SNS::Topic.new self.topic_arn
    topic_subscriptions = topic.subscriptions
    missing_arn.each do |s|
      topic_subscriptions.each do |ts|
        if ts.endpoint.to_s == s.endpoint.to_s && ts.protocol.to_s == s.protocol.to_s
          s.update_attribute(:subscription_arn, ts.arn)
          break
        end
      end
    end
    return subscriptions
  end
    
  def save_sns
    topic_collection = AWS::SNS::TopicCollection.new
    topic = topic_collection.create name
    topic.display_name = name
    self.topic_arn = topic.arn
  end
  
  def delete_sns  
    topic = AWS::SNS::Topic.new self.topic_arn
    topic.delete
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate
  
  def index
    @campaigns = Campaign.find_all_by_account_id(current_user.account_id)
  end
  
  def new
    @campaign = Campaign.new
  end
  
  def show
    @account = current_user.account
    @campaign = @account.campaigns.find(params[:id])
    @subscriptions = @campaign.subscriptions
  end
  
  def create
    @campaign = Campaign.new(params[:campaign])
    @campaign.account_id = current_user.account_id
    
    if @campaign.save
      flash[:notice] = "Campaign created!"
      redirect_to campaign_path(@campaign)
    else
      render :action => "new"
    end      
  end
  
  def destroy
    @account = current_user.account
    @campaign = @account.campaigns.find(params[:id])    
    @campaign.destroy
    flash[:notice] = "Campaign deleted!"
    
    redirect_to campaigns_path
  end
end

app/views/campaigns/_campaign.html.erb
<li>
  <%= link_to campaign.name, campaign_path(campaign) %>
  <span class=' ui-li-count'><%= campaign.messages_count %> sent messages</span>
</li>

app/views/campaigns/index.html.erb
<% content_for :right_header do %>
  <%= link_to 'Add New Campaign', new_campaign_path, 'data-theme' => 'a', 'data-icon' => 'plus', 'class' => 'ui-btn-right' %>
<% end %>

<div class="ui-body ui-body-a">
  <h2>Campaigns</h2>
  <ul data-role="listview" data-theme="d" data-inset="true">

	<% unless @campaigns.blank? %>
      <%= render @campaigns %>
    <% else %>
      <li data-role="list-divider"><h4>No Campaigns</h4></li>
    <% end %>
  </ul>
</div>

app/views/campaigns/new.html.erb
<div class="ui-body ui-body-a">
  <h1>New Campaign</h1>

  <%= form_for(@campaign) do |f| %>
    <p>
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name %>
    </p>
    <p><%= f.submit 'Save' %></p>
  <% end %>
  <br />
</div>	
<%= render "layouts/partials/validation_errors", :model => @campaign %>

app/views/campaigns/show.html.erb
<% content_for :right_header do %>
  <%= link_to 'Send Messsage', new_campaign_message_path(@campaign), 'data-theme' => 'a', 'data-icon' => 'plus', 'class' => 'ui-btn-right' %>
<% end %>

<div class="ui-body ui-body-a">
  <h1>Campaign: <%= @campaign.name %></h1>
  <div class="ui-body ui-body-b">
    <h4>Messages Sent: 0</h4>	
  </div>

  <h2>Contacts:</h2>
  <ul data-role="listview" data-theme="d" data-inset="true">
	<% if @subscriptions %>
      <%= render @subscriptions %>
    <% else %>
      <li data-role="list-divider">No subscribed contacts</li>
    <% end %>
  </ul>

  <%= form_for(@campaign, :method => :delete) do |f| %>
    <p><%= f.submit 'Delete Campaign and Subscriptions', 'data-inline' => true, 'data-icon' => 'delete' %></p>
  <% end %>
</div>