config/routes.rb
TheSwarm::Application.routes.draw do
  resource :account, :only => [:show,:edit,:update], :controller => 'accounts'
  resources :users, :only => [:index,:new,:create]
  resource :user, :only => [:edit,:update], :controller => 'users'
  
  resources :campaigns, :only => [:index,:show,:new,:create,:destroy] do
    resources :messages, :only => [:new,:create,:show]
  end
  
  resources :contacts do
    resources :subscriptions, :only => [:new,:create,:destroy]
  end
  
  resource :login, :only => [:new,:create,:destroy]

  root :to => 'campaigns#index'
end

app/views/layouts/partials/_footer.html.erb
<div data-role="footer">	
  <center><p>KBNS (Killer Bee Notification System) &copy; Bellwether</p></center>
</div>

app/views/layouts/partials/_header.html.erb
<div data-role='header'>
  <%= yield :left_header %>
  <h1>The Swarm</h1>
  <%= yield :right_header %>
</div>
<div data-role='navbar' data-iconpos='left'>
  <ul>
    <li><%= link_to 'Dashboard', account_path, 'data-theme' => 'a', 'data-icon' => 'home' %></li>
    <li><%= link_to 'Campaigns', campaigns_path, 'data-theme' => 'a', 'data-icon' => 'grid' %></li>
    <li><%= link_to 'Contacts', contacts_path, 'data-theme' => 'a', 'data-icon' => 'star' %></li>
  </ul>
</div>

app/views/layouts/partials/_validation_errors.html.erb
<% if model.errors.any? %>
  <div id='errors' class='ui-screen-hidden'>
	<div style='padding:15px;'>
      <h3>Error : Could not Save</h3>
      <p><%= model.errors.full_messages.join(', ') %></p>
    </div>
	<a rel='close' data-role='button' href='#' id='simpleclose'>Ok</a>
  </div>
<% end %>